# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{webidl}
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jari Bakken"]
  s.date = %q{2010-08-20}
  s.default_executable = %q{webidl2ruby}
  s.description = %q{Built on Treetop, this gem will parse an interface declaration in WebIDL and generate ruby code}
  s.email = %q{jari.bakken@gmail.com}
  s.executables = ["webidl2ruby"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/webidl2ruby",
     "examples/html5.rb",
     "lib/webidl.rb",
     "lib/webidl/ast/argument.rb",
     "lib/webidl/ast/attribute.rb",
     "lib/webidl/ast/const.rb",
     "lib/webidl/ast/exception.rb",
     "lib/webidl/ast/extended_attribute.rb",
     "lib/webidl/ast/field.rb",
     "lib/webidl/ast/implements_statement.rb",
     "lib/webidl/ast/interface.rb",
     "lib/webidl/ast/module.rb",
     "lib/webidl/ast/node.rb",
     "lib/webidl/ast/operation.rb",
     "lib/webidl/ast/scoped_name.rb",
     "lib/webidl/ast/type.rb",
     "lib/webidl/ast/typedef.rb",
     "lib/webidl/extensions/string.rb",
     "lib/webidl/extensions/syntax_node.rb",
     "lib/webidl/generator.rb",
     "lib/webidl/generator/ruby_sexp_visitor.rb",
     "lib/webidl/parse_tree/absolute_scoped_name.rb",
     "lib/webidl/parse_tree/argument.rb",
     "lib/webidl/parse_tree/argument_list.rb",
     "lib/webidl/parse_tree/attribute.rb",
     "lib/webidl/parse_tree/const.rb",
     "lib/webidl/parse_tree/definitions.rb",
     "lib/webidl/parse_tree/exception.rb",
     "lib/webidl/parse_tree/exception_field.rb",
     "lib/webidl/parse_tree/extended_attributes.rb",
     "lib/webidl/parse_tree/implements_statement.rb",
     "lib/webidl/parse_tree/interface.rb",
     "lib/webidl/parse_tree/interface_inheritance.rb",
     "lib/webidl/parse_tree/interface_members.rb",
     "lib/webidl/parse_tree/module.rb",
     "lib/webidl/parse_tree/nullable_type.rb",
     "lib/webidl/parse_tree/operation.rb",
     "lib/webidl/parse_tree/relative_scoped_name.rb",
     "lib/webidl/parse_tree/scoped_name_list.rb",
     "lib/webidl/parse_tree/specials.rb",
     "lib/webidl/parse_tree/stringifier_attribute_or_operation.rb",
     "lib/webidl/parse_tree/type.rb",
     "lib/webidl/parse_tree/typedef.rb",
     "lib/webidl/parser/debug_helper.rb",
     "lib/webidl/parser/idl.rb",
     "lib/webidl/parser/idl.treetop",
     "spec/ast_spec.rb",
     "spec/fixtures/empty_interface.idl",
     "spec/fixtures/empty_module.idl",
     "spec/fixtures/framework.idl",
     "spec/fixtures/html5.idl",
     "spec/fixtures/interface_with_array_member.idl",
     "spec/fixtures/interface_with_attribute.idl",
     "spec/fixtures/interface_with_inheritance.idl",
     "spec/fixtures/interface_with_members.idl",
     "spec/fixtures/interface_with_specials.idl",
     "spec/fixtures/interface_with_stringifiers.idl",
     "spec/fixtures/module_with_exception.idl",
     "spec/fixtures/module_with_implements_statement.idl",
     "spec/fixtures/module_with_typedef.idl",
     "spec/fixtures/module_with_xattr_ident.idl",
     "spec/fixtures/module_with_xattr_named_args.idl",
     "spec/fixtures/module_with_xattr_no_arg.idl",
     "spec/fixtures/module_with_xattr_scoped.idl",
     "spec/fixtures/module_with_xattr_two_args.idl",
     "spec/fixtures/nested.idl",
     "spec/fixtures/websocket.idl",
     "spec/generator_spec.rb",
     "spec/parser_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "support/webidl-spec-2010-08-05.html",
     "webidl.gemspec"
  ]
  s.homepage = %q{http://github.com/jarib/webidl}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{WebIDL parser/generator for ruby}
  s.test_files = [
    "spec/parser_spec.rb",
     "spec/ast_spec.rb",
     "spec/generator_spec.rb",
     "spec/spec_helper.rb",
     "examples/html5.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<treetop>, [">= 0"])
      s.add_runtime_dependency(%q<ruby2ruby>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<treetop>, [">= 0"])
      s.add_dependency(%q<ruby2ruby>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<treetop>, [">= 0"])
    s.add_dependency(%q<ruby2ruby>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

