require "treetop"
require "ruby2ruby"

require "webidl/extensions/syntax_node"
require "webidl/extensions/string"

require "webidl/parse_tree/definitions"
require "webidl/parse_tree/module"
require "webidl/parse_tree/attribute"
require "webidl/parse_tree/typedef"
require "webidl/parse_tree/inheritance"
require "webidl/parse_tree/interface"
require "webidl/parse_tree/interface_members"
require "webidl/parse_tree/partial_interface"
require "webidl/parse_tree/argument"
require "webidl/parse_tree/argument_list"
require "webidl/parse_tree/dictionary"
require "webidl/parse_tree/dictionary_members"
require "webidl/parse_tree/dictionary_member"
require "webidl/parse_tree/extended_attributes"
require "webidl/parse_tree/relative_scoped_name"
require "webidl/parse_tree/absolute_scoped_name"
require "webidl/parse_tree/sequence_type"
require "webidl/parse_tree/type_suffix"
require "webidl/parse_tree/type"
require "webidl/parse_tree/operation"
require "webidl/parse_tree/const"
require "webidl/parse_tree/specials"
require "webidl/parse_tree/exception"
require "webidl/parse_tree/exception_field"
require "webidl/parse_tree/implements_statement"
require "webidl/parse_tree/scoped_name_list"
require "webidl/parse_tree/stringifier_attribute_or_operation"

require "webidl/ast/node"
require "webidl/ast/module"
require "webidl/ast/typedef"
require "webidl/ast/interface"
require "webidl/ast/dictionary"
require "webidl/ast/dictionary_member"
require "webidl/ast/extended_attribute"
require "webidl/ast/argument"
require "webidl/ast/type"
require "webidl/ast/scoped_name"
require "webidl/ast/operation"
require "webidl/ast/const"
require "webidl/ast/sequence"
require "webidl/ast/exception"
require "webidl/ast/attribute"
require "webidl/ast/field"
require "webidl/ast/implements_statement"

require "webidl/parser/debug_helper"
require "webidl/parser/idl"

require "webidl/generator"
require "webidl/generator/ruby_sexp_visitor"
